### ISSUE TITLE
Epic: Polish Cluster support

### ISSUE THREAD

**Issue by khionu** [rsimmonsjr/axiom#114]
In order for Cluster support to be more polished, we need to do the following:
- [ ] Move Cluster connection threads into the Executor
- [ ] Remove the panics and introduce better errors/logging into the Cluster APIs
- [ ] Introduce a way to reconnect Clusters that disconnect

**Comment by khionu** [comment]
If someone could tackle this, we could put it into the 0.3.0 release.
